spring:
  application:
    name: Its an order - API
    # H2
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
      show-sql: true
      format_sql: true
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/test

hibernate:
  temp:
    use_jdbc_metadata_defaults: false

api:
  cors:
    enabled: true