spring:
  application:
    name: Its an order - API
  datasource:
    username: postgres
    password: a
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.17.0.12:5432/api

api:
  cors:
    enabled: true