CREATE TABLE ORDER_STATUS (
    ID                  INTEGER         NOT NULL,
    DESCRIPTION         VARCHAR(120)    NOT NULL,

    CONSTRAINT PK_ORDER_STATUS PRIMARY KEY (ID)
);

INSERT INTO ORDER_STATUS (ID, DESCRIPTION) VALUES (1, 'Created');
INSERT INTO ORDER_STATUS (ID, DESCRIPTION) VALUES (2, 'Accepted');
INSERT INTO ORDER_STATUS (ID, DESCRIPTION) VALUES (3, 'Preparing');
INSERT INTO ORDER_STATUS (ID, DESCRIPTION) VALUES (4, 'On the way');
INSERT INTO ORDER_STATUS (ID, DESCRIPTION) VALUES (5, 'Cancelled');
INSERT INTO ORDER_STATUS (ID, DESCRIPTION) VALUES (6, 'Deliveried');

CREATE TABLE CUSTOMER (
    ID                  SERIAL          NOT NULL,
    EMAIL               VARCHAR(200)    NOT NULL,
    PASSWORD            VARCHAR(100)    NOT NULL,
    FULL_NAME           VARCHAR(200)    NOT NULL,
    FULL_ADDRESS        VARCHAR(500)    NOT NULL,
    CREATION_DATE       TIMESTAMP       NOT NULL,

    CONSTRAINT PK_CUSTOMER PRIMARY KEY (ID)
);

CREATE TABLE COUSINE (
    ID                  SERIAL          NOT NULL,
    DESCRIPTION         VARCHAR(200)    NOT NULL,

    CONSTRAINT PK_COUSINE PRIMARY KEY (ID)
);

CREATE TABLE STORE (
    ID                  SERIAL          NOT NULL,
    NAME                VARCHAR(120)    NOT NULL,
    FULL_ADDRESS        VARCHAR(500)    NOT NULL,
    COUSINE_ID          INTEGER         NOT NULL,

    CONSTRAINT PK_STORE PRIMARY KEY (ID),
    CONSTRAINT FK_STORE_COUSINE FOREIGN KEY (COUSINE_ID) REFERENCES COUSINE (ID)
);

CREATE TABLE PRODUCT (
    ID                  SERIAL          NOT NULL,
    STORE_ID            INTEGER         NOT NULL,
    NAME                VARCHAR(120)    NOT NULL,
    DESCRIPTION         VARCHAR         NOT NULL,
    PRICE               NUMERIC(15, 2)  NOT NULL,

    CONSTRAINT PK_PRODUCT PRIMARY KEY (ID),
    CONSTRAINT FK_PRODUCT_STORE FOREIGN KEY (STORE_ID) REFERENCES STORE (ID)
);

CREATE TABLE ORDERS (
    ID                  SERIAL          NOT NULL,
    CREATION_DATE       TIMESTAMP       NOT NULL,
    DELIVERY_ADDRESS    VARCHAR(500)    NOT NULL,
    CONTACT             VARCHAR(200)    NOT NULL,
    CUSTOMER_ID         INTEGER         NOT NULL,
    STORE_ID            INTEGER         NOT NULL,
    TOTAL               NUMERIC(15, 2)  NOT NULL,
    STATUS_ID           INTEGER         NOT NULL,
    LAST_UPDATE         TIMESTAMP       NOT NULL,

    CONSTRAINT PK_ORDERS PRIMARY KEY (ID),
    CONSTRAINT FK_ORDERS_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID),
    CONSTRAINT FK_ORDERS_STORE FOREIGN KEY (STORE_ID) REFERENCES STORE (ID),
    CONSTRAINT FK_ORDERS_STATUS FOREIGN KEY (STATUS_ID) REFERENCES ORDER_STATUS (ID)
);

CREATE TABLE ORDER_ITEM (
    ID                  SERIAL          NOT NULL,
    ORDER_ID            INTEGER         NOT NULL,
    PRODUCT_ID          INTEGER         NOT NULL,
    PRICE               NUMERIC(15, 2)  NOT NULL,
    QUANTITY            INTEGER         NOT NULL,
    TOTAL               NUMERIC(15, 2)  NOT NULL,

    CONSTRAINT PK_ORDER_ITEM PRIMARY KEY (ID),
    CONSTRAINT FK_ORDER_ITEM_ORDERS FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ID),
    CONSTRAINT FK_ORDER_ITEM_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);